backend:
  name: git-gateway
  branch: master
   # Branch to update (optional; defaults to master)

media_folder: public/img
public_folder: /img

collections:
  - name: 'data'
    label: 'Data'
    folder: 'public/'
    format: 'json'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Sub-title', name: 'subTitle', widget: 'string' }
      - { label: 'Youtube link', name: 'youtubeLink', widget: 'string' }
      - { label: 'Video description', name: 'videoDescription', widget: 'markdown' }
      - { label: 'Call to Action', name: 'callToAction', widget: 'string'}
      - { label: 'Aspirational Text 1', name: 'aspirationalText1', widget: 'string'}
      - { label: 'Aspirational Text 2', name: 'aspirationalText2', widget: 'string'}